export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/Auth/login",
    REGISTER: "/api/Auth/register",
    LOGOUT: "/api/Auth/logout",
    REFRESH_TOKEN: "/api/Auth/refresh",
    ME: "/api/Auth/me",
    VERIFY_EMAIL: "/api/Auth/verify-email",
    FORGOT_PASSWORD: "/api/Auth/forgot-password",
    RESET_PASSWORD: "/api/Auth/reset-password",
    CHANGE_PASSWORD: "/api/Auth/change-password",
  },
  SESSION: {
    LIST: "/api/Sessions",
    CREATE: "/api/Sessions",
    GET: (id: string) => `/api/Sessions/${id}`,
    UPDATE: (id: string) => `/api/Sessions/${id}`,
    DELETE: (id: string) => `/api/Sessions/${id}`,
    FINALIZE: (id: string) => `/api/Sessions/${id}/finalize`,
  },
  CATEGORY: {
    LIST: "/api/Categories",
    GET: (id: string) => `/api/Categories/${id}`,
    CREATE: "/api/Categories",
    UPDATE: (id: string) => `/api/Categories/${id}`,
    DELETE: (id: string) => `/api/Categories/${id}`,
  },
  DISH: {
    LIST: "/api/Dishes",
    GET: (id: string) => `/api/Dishes/${id}`,
    CREATE: "/api/Dishes",
    UPDATE: (id: string) => `/api/Dishes/${id}`,
    UPDATE_STOCK: (id: string) => `/api/Dishes/${id}/stock`,
    DELETE: (id: string) => `/api/Dishes/${id}`,
  },
  ORDER: {
    LIST: "/api/Orders",
    GET: (id: string) => `/api/Orders/${id}`,
    CREATE: "/api/Orders",
    UPDATE: (id: string) => `/api/Orders/${id}`,
    DELETE: (id: string) => `/api/Orders/${id}`,
    MANAGER_BY_SESSION: (sessionId: string) => `/api/manager/orders/session/${sessionId}`,
  },
  CART: {
    GET: "/api/Cart",
    UPDATE: "/api/Cart",
    DELETE: "/api/Cart",
  },
  PAYMENT: {
    TOP_UP: "/api/Payments/top-up",
    TOP_UP_POLICY: "/api/Payments/top-up-policy",
    GET: (id: string) => `/api/Payments/${id}`,
  },
  WALLET: {
    TRANSACTIONS: "/api/Wallet/transactions",
    GET: (id: string) => `/api/Wallet/transactions/${id}`,
  },
  SETTINGS: {
    LIST: "/api/Settings",
    CREATE: "/api/Settings",
    GET: (id: string) => `/api/Settings/${id}`,
    UPDATE: (id: string) => `/api/Settings/${id}`,
    DELETE: (id: string) => `/api/Settings/${id}`,
  },
  REFUND: {
    LIST: "/api/refunds",
    CREATE: "/api/refunds",
    GET: (id: string) => `/api/refunds/${id}`,
    MANAGER_LIST: "/api/manager/refunds",
    MANAGER_GET: (id: string) => `/api/manager/refunds/${id}`,
    MANAGER_APPROVE: (id: string) => `/api/manager/refunds/${id}/approve`,
    MANAGER_REJECT: (id: string) => `/api/manager/refunds/${id}/reject`,
    POLICIES: "/api/refund-policies",
    MANAGER_POLICIES: "/api/manager/refund-policies",
    MANAGER_POLICY_CREATE: "/api/manager/refund-policies",
    MANAGER_POLICY_UPDATE: (code: string) => `/api/manager/refund-policies/${code}`,
    MANAGER_POLICY_DELETE: (code: string) => `/api/manager/refund-policies/${code}`,
  },
  VERIFICATION: {
    SUBMIT: "/api/Verification/submit",
    ME: "/api/Verification/me",
    ADMIN_LIST: "/api/admin/verifications",
    ADMIN_GET: (id: string) => `/api/admin/verifications/${id}`,
    ADMIN_APPROVE: (id: string) => `/api/admin/verifications/${id}/approve`,
    ADMIN_REJECT: (id: string) => `/api/admin/verifications/${id}/reject`,
  },
  NOTIFICATION: {
    LIST: "/api/notifications",
    UNREAD_COUNT: "/api/notifications/unread-count",
    READ: (id: string) => `/api/notifications/${id}/read`,
    READ_ALL: "/api/notifications/read-all",
    DELETE: (id: string) => `/api/notifications/${id}`,
  },
  CHANGE_PROPOSAL: {
    LIST: "/api/ChangeProposals",
    ACCEPT: (id: string) => `/api/ChangeProposals/${id}/accept`,
    REQUEST_REFUND: (id: string) => `/api/ChangeProposals/${id}/request-refund`,
  },
  PICKUP: {
    ASSIGN: "/api/pickup/assign",
    COLLECT: "/api/pickup/collect",
  },
  ROBOT: {
    SERVING_JOBS: "/api/robot/serving-jobs",
  },
  ADMIN: {
    LOGS: {
      LIST: "/api/admin/logs",
      GET: (id: string) => `/api/admin/logs/${id}`,
    },
  },
} as const;
