export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/Auth/login",
    REGISTER: "/api/Auth/register",
    LOGOUT: "/api/Auth/logout",
    REFRESH_TOKEN: "/api/Auth/refresh",
    ME: "/api/Auth/me",
    VERIFY_EMAIL: "/api/Auth/verify-email",
    FORGOT_PASSWORD: "/api/Auth/forgot-password",
    RESET_PASSWORD: "/api/Auth/reset-password",
    CHANGE_PASSWORD: "/api/Auth/change-password",
  },
  SESSION: {
    LIST: "/api/Sessions",
    CREATE: "/api/Sessions",
    GET: (id: string) => `/api/Sessions/${id}`,
    UPDATE: (id: string) => `/api/Sessions/${id}`,
    DELETE: (id: string) => `/api/Sessions/${id}`,
    FINALIZE: (id: string) => `/api/Sessions/${id}/finalize`,
    CALENDAR: "/api/sessions/calendar",
  },
  CATEGORY: {
    LIST: "/api/Categories",
    GET: (id: string) => `/api/Categories/${id}`,
    CREATE: "/api/Categories",
    UPDATE: (id: string) => `/api/Categories/${id}`,
    DELETE: (id: string) => `/api/Categories/${id}`,
  },
  DISH: {
    LIST: "/api/Dishes",
    GET: (id: string) => `/api/Dishes/${id}`,
    CREATE: "/api/Dishes",
    UPDATE: (id: string) => `/api/Dishes/${id}`,
    UPDATE_STOCK: (id: string) => `/api/Dishes/${id}/stock`,
    DELETE: (id: string) => `/api/Dishes/${id}`,
  },
  ORDER: {
    LIST: "/api/Orders",
    GET: (id: string) => `/api/Orders/${id}`,
    CREATE: "/api/Orders",
    UPDATE: (id: string) => `/api/Orders/${id}`,
    DELETE: (id: string) => `/api/Orders/${id}`,
    MANAGER_BY_SESSION: (sessionId: string) => `/api/manager/orders/session/${sessionId}`,
    MANAGER_GET: (id: string) => `/api/manager/orders/${id}`,
    MANAGER_UPDATE_STATUS: (id: string) => `/api/manager/orders/${id}/status`,
  },
  CART: {
    GET: "/api/Cart",
    UPDATE: "/api/Cart",
    DELETE: "/api/Cart",
  },
  PAYMENT: {
    TOP_UP: "/api/Payments/top-up",
    TOP_UP_POLICY: "/api/Payments/top-up-policy",
    GET: (id: string) => `/api/Payments/${id}`,
  },
  WALLET: {
    TRANSACTIONS: "/api/wallet-transactions",
    GET: (id: string) => `/api/wallet-transactions/${id}`,
  },
  SETTINGS: {
    LIST: "/api/Settings",
    CREATE: "/api/Settings",
    GET: (id: string) => `/api/Settings/${id}`,
    UPDATE: (id: string) => `/api/Settings/${id}`,
    DELETE: (id: string) => `/api/Settings/${id}`,
  },
  REFUND: {
    LIST: "/api/refunds",
    CREATE: "/api/refunds",
    GET: (id: string) => `/api/refunds/${id}`,
    MANAGER_LIST: "/api/manager/refunds",
    MANAGER_GET: (id: string) => `/api/manager/refunds/${id}`,
    MANAGER_APPROVE: (id: string) => `/api/manager/refunds/${id}/approve`,
    MANAGER_REJECT: (id: string) => `/api/manager/refunds/${id}/reject`,
    POLICIES: "/api/refund-policies",
    MANAGER_POLICIES: "/api/manager/refund-policies",
    MANAGER_POLICY_CREATE: "/api/manager/refund-policies",
    MANAGER_POLICY_UPDATE: (code: string) => `/api/manager/refund-policies/${code}`,
    MANAGER_POLICY_DELETE: (code: string) => `/api/manager/refund-policies/${code}`,
  },
  MANAGER_USERS: {
    LIST: "/api/manager/users",
    GET: (id: string) => `/api/manager/users/${id}`,
    SUSPEND: (id: string) => `/api/manager/users/${id}/suspend`,
    BAN: (id: string) => `/api/manager/users/${id}/ban`,
    REACTIVATE: (id: string) => `/api/manager/users/${id}/reactivate`,
  },
  VERIFICATION: {
    SUBMIT: "/api/Verification/submit",
    ME: "/api/Verification/me",
    ADMIN_LIST: "/api/admin/verifications",
    ADMIN_GET: (id: string) => `/api/admin/verifications/${id}`,
    ADMIN_APPROVE: (id: string) => `/api/admin/verifications/${id}/approve`,
    ADMIN_REJECT: (id: string) => `/api/admin/verifications/${id}/reject`,
  },
  NOTIFICATION: {
    LIST: "/api/notifications",
    UNREAD_COUNT: "/api/notifications/unread-count",
    READ: (id: string) => `/api/notifications/${id}/read`,
    READ_ALL: "/api/notifications/read-all",
    DELETE: (id: string) => `/api/notifications/${id}`,
  },
  CHANGE_PROPOSAL: {
    LIST: "/api/ChangeProposals",
    GET: (id: string) => `/api/ChangeProposals/${id}`,
    ACCEPT: (id: string) => `/api/ChangeProposals/${id}/accept`,
    REQUEST_REFUND: (id: string) => `/api/ChangeProposals/${id}/request-refund`,
    REQUEST_ORDER_REFUND: (id: string) => `/api/ChangeProposals/${id}/request-order-refund`,
  },
  PICKUP: {
    ASSIGN: "/api/pickup/assign",
    COLLECT: "/api/pickup/collect",
  },
  ROBOT: {
    SERVING_JOBS: "/api/robot/serving-jobs",
  },
  MANAGER: {
    ROBOT_ARMS: {
      LIST: "/api/manager/robot-arms",
      GET: (id: string) => `/api/manager/robot-arms/${id}`,
      CREATE: "/api/manager/robot-arms",
      UPDATE: (id: string) => `/api/manager/robot-arms/${id}`,
      DELETE: (id: string) => `/api/manager/robot-arms/${id}`,
      MAINTENANCE: (id: string) => `/api/manager/robot-arms/${id}/maintenance`,
    },
    TRAYS: {
      LIST: "/api/manager/trays",
      GET_BY_ID: (id: string) => `/api/manager/trays/${id}`,
      CREATE: "/api/manager/trays",
      FORCE_RELEASE: (id: string) => `/api/manager/trays/${id}/force-release`,
      RETIRE: (id: string) => `/api/manager/trays/${id}/retire`,
    },
    PICKUP_SLOTS: {
      LIST: "/api/manager/pickup-slots",
      CREATE: "/api/manager/pickup-slots",
      FORCE_CLEAR: (id: string) => `/api/manager/pickup-slots/${id}/force-clear`,
      RETIRE: (id: string) => `/api/manager/pickup-slots/${id}/retire`,
    },
    SLOT_CONFIGURATIONS: {
      LIST_BY_SESSION: (sessionId: string) =>
        `/api/manager/slot-configurations?sessionId=${sessionId}`,
      GET: (id: string) => `/api/manager/slot-configurations/${id}`,
      CREATE: "/api/manager/slot-configurations",
      UPDATE: (id: string) => `/api/manager/slot-configurations/${id}`,
      DELETE: (id: string) => `/api/manager/slot-configurations/${id}`,
    },
    SHELF_STOCKS: {
      LIST_BY_SESSION: (sessionId: string) => `/api/manager/shelf-stocks?sessionId=${sessionId}`,
      GET: (id: string) => `/api/manager/shelf-stocks/${id}`,
      CREATE: "/api/manager/shelf-stocks",
      UPDATE: (id: string) => `/api/manager/shelf-stocks/${id}`,
      DELETE: (id: string) => `/api/manager/shelf-stocks/${id}`,
      LIST_BY_ARM: (armId: string) => `/api/manager/shelf-stocks?armId=${armId}`,
      LIST_BY_DISH: (dishId: string) => `/api/manager/shelf-stocks?dishId=${dishId}`,
    },
  },
  ADMIN: {
    LOGS: {
      LIST: "/api/admin/logs",
      GET: (id: string) => `/api/admin/logs/${id}`,
    },
  },
  REPORT: {
    SUMMARY: "/api/manager/reports/summary",
    SESSIONS: "/api/manager/reports/sessions",
    SESSION_DETAIL: (sessionId: string) => `/api/manager/reports/sessions/${sessionId}`,
    ORDER_ISSUES: "/api/manager/reports/order-issues",
    REFUND_POLICIES: "/api/manager/reports/refund-policies",
  },
} as const;
